import { initialBoostedPosts } from "../mock-data/boostedPosts";
import type {
  BoostedPost,
  BoostedPostStatus,
  BoostedPostSummaryCard,
} from "../types/boostedPost";

export const boostedPostService = {
  getBoostedPosts(): BoostedPost[] {
    return initialBoostedPosts;
  },

  getSummaryCards(posts: BoostedPost[]): BoostedPostSummaryCard[] {
    const activeCount = posts.filter((item) => item.status === "Active").length;
    const pausedCount = posts.filter((item) => item.status === "Paused").length;
    const scheduledCount = posts.filter(
      (item) => item.status === "Scheduled",
    ).length;
    const totalImpressions = posts.reduce(
      (sum, item) => sum + item.impressions,
      0,
    );
    const totalClicks = posts.reduce((sum, item) => sum + item.clicks, 0);

    return [
      {
        title: "Active Campaigns",
        value: String(activeCount),
        subtitle: "Currently delivering boosted placements",
      },
      {
        title: "Paused Campaigns",
        value: String(pausedCount),
        subtitle: "Temporarily stopped by admin review",
      },
      {
        title: "Scheduled Campaigns",
        value: String(scheduledCount),
        subtitle: "Ready to start in upcoming promotion windows",
      },
      {
        title: "Total Impressions",
        value: totalImpressions.toLocaleString("en-US"),
        subtitle: "Combined delivered impressions across all campaigns",
      },
      {
        title: "Total Clicks",
        value: totalClicks.toLocaleString("en-US"),
        subtitle: "Combined click volume generated by boosted posts",
      },
    ];
  },

  updateBoostedPostStatus(
    posts: BoostedPost[],
    postId: number,
    status: BoostedPostStatus,
  ): BoostedPost[] {
    return posts.map((item) =>
      item.id === postId ? { ...item, status } : item,
    );
  },
};
