import type { BoostedPost } from "../types/boostedPost";

export const initialBoostedPosts: BoostedPost[] = [
  {
    id: 1,
    campaignCode: "BST-BOOSTPOST-0015",
    postTitle: "Tùng Bách Tán Lùn Nhật Mini",
    ownerName: "Nam Định Art Garden",
    slot: "Vị trí 1 trang chủ",
    packageName: "Gói đẩy bài theo tháng vị trí 1 trang chủ",
    startDate: "2026-04-11",
    endDate: "2026-05-10",
    status: "Paused",
    deliveryHealth: "Watch",
    reviewStatus: "Approved",
    assignedOperator: "Nhóm vận hành A",
    totalQuota: 180000,
    usedQuota: 54000,
    impressions: 54000,
    clicks: 1328,
    lastOptimizedAt: "2026-04-15 11:58",
    notes:
      "Chiến dịch vị trí 1 đang tạm dừng để chờ admin rà soát lại phân bổ hiển thị.",
  },
  {
    id: 2,
    campaignCode: "BST-BOOSTPOST2-0011",
    postTitle: "Kim Quýt Bonsai Mini Sai Quả",
    ownerName: "Vườn Bonsai Phố Huyện",
    slot: "Vị trí 2 trang chủ",
    packageName: "Gói đẩy bài theo tháng vị trí 2 trang chủ",
    startDate: "2026-04-12",
    endDate: "2026-05-11",
    status: "Paused",
    deliveryHealth: "Watch",
    reviewStatus: "Needs Update",
    assignedOperator: "Nhóm vận hành A",
    totalQuota: 35000,
    usedQuota: 10500,
    impressions: 10500,
    clicks: 259,
    lastOptimizedAt: "2026-04-16 04:13",
    notes:
      "Chiến dịch vị trí 2 đang tạm dừng để kiểm tra lại nội dung bài đăng trước khi tiếp tục.",
  },
  {
    id: 3,
    campaignCode: "BST-BOOSTPOST3-0014",
    postTitle: "Sanh Nam Điền Mini Dáng Văn Nhân",
    ownerName: "Vườn Bonsai Phố Huyện",
    slot: "Vị trí 3 trang chủ",
    packageName: "Gói đẩy bài theo tháng vị trí 3 trang chủ",
    startDate: "2026-04-16",
    endDate: "2026-05-16",
    status: "Active",
    deliveryHealth: "Healthy",
    reviewStatus: "Approved",
    assignedOperator: "Nhóm vận hành A",
    totalQuota: 5000,
    usedQuota: 900,
    impressions: 900,
    clicks: 26,
    lastOptimizedAt: "2026-04-15 11:58",
    notes:
      "Chiến dịch vị trí 3 đang chạy ổn định, quota mới dùng ở mức thấp nên còn dư cho cả chu kỳ.",
  },
];
