import type { BoostedPost } from "../types/boostedPost";

export const initialBoostedPosts: BoostedPost[] = [
  {
    id: 1,
    campaignCode: "BST-HOME-2401",
    postTitle: "Rare Monstera Deliciosa for Sale",
    ownerName: "Nguyen Van A",
    slot: "Home Top",
    packageName: "Homepage Premium 7 Days",
    startDate: "2026-03-15",
    endDate: "2026-03-22",
    status: "Active",
    deliveryHealth: "Healthy",
    reviewStatus: "Approved",
    assignedOperator: "Ops Team A",
    totalQuota: 50000,
    usedQuota: 18240,
    impressions: 18240,
    clicks: 536,
    lastOptimizedAt: "2026-03-20 10:30",
    notes:
      "Stable homepage delivery with healthy CTR and no manual intervention needed.",
  },
  {
    id: 2,
    campaignCode: "BST-CAT-2407",
    postTitle: "Mini Bonsai Collection",
    ownerName: "Tran Thi B",
    slot: "Category Top",
    packageName: "Category Spotlight 5 Days",
    startDate: "2026-03-14",
    endDate: "2026-03-19",
    status: "Paused",
    deliveryHealth: "Watch",
    reviewStatus: "Needs Update",
    assignedOperator: "Ops Team B",
    totalQuota: 25000,
    usedQuota: 9400,
    impressions: 9400,
    clicks: 224,
    lastOptimizedAt: "2026-03-18 14:05",
    notes:
      "Paused while waiting for refreshed banner image and category headline update.",
  },
  {
    id: 3,
    campaignCode: "BST-SRC-2410",
    postTitle: "Succulent Combo Pot Set",
    ownerName: "Le Van C",
    slot: "Search Boost",
    packageName: "Search Boost 3 Days",
    startDate: "2026-03-10",
    endDate: "2026-03-13",
    status: "Expired",
    deliveryHealth: "At Risk",
    reviewStatus: "Escalated",
    assignedOperator: "Ops Team C",
    totalQuota: 15000,
    usedQuota: 15000,
    impressions: 15000,
    clicks: 301,
    lastOptimizedAt: "2026-03-13 16:40",
    notes:
      "Campaign expired after search relevance dropped and escalation ticket was closed.",
  },
  {
    id: 4,
    campaignCode: "BST-HOME-2415",
    postTitle: "Philodendron Pink Princess Cutting",
    ownerName: "Pham Thi D",
    slot: "Home Top",
    packageName: "Homepage Premium 7 Days",
    startDate: "2026-04-02",
    endDate: "2026-04-09",
    status: "Scheduled",
    deliveryHealth: "Watch",
    reviewStatus: "Approved",
    assignedOperator: "Ops Team A",
    totalQuota: 50000,
    usedQuota: 0,
    impressions: 0,
    clicks: 0,
    lastOptimizedAt: "2026-04-01 09:00",
    notes:
      "Prepared for next homepage window and queued for opening quality check.",
  },
  {
    id: 5,
    campaignCode: "BST-SRC-2419",
    postTitle: "Variegated Alocasia Showcase",
    ownerName: "Hoang Van E",
    slot: "Search Boost",
    packageName: "Search Boost 5 Days",
    startDate: "2026-03-20",
    endDate: "2026-03-25",
    status: "Active",
    deliveryHealth: "Healthy",
    reviewStatus: "Approved",
    assignedOperator: "Ops Team C",
    totalQuota: 24000,
    usedQuota: 16200,
    impressions: 16200,
    clicks: 488,
    lastOptimizedAt: "2026-03-22 11:15",
    notes:
      "Keyword bid tuning improved search rank and maintained strong click quality.",
  },
  {
    id: 6,
    campaignCode: "BST-CAT-2422",
    postTitle: "Ficus Ginseng Decorative Pot",
    ownerName: "Hoang Van E",
    slot: "Category Top",
    packageName: "Category Spotlight 5 Days",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "Completed",
    deliveryHealth: "Healthy",
    reviewStatus: "Approved",
    assignedOperator: "Ops Team B",
    totalQuota: 25000,
    usedQuota: 25000,
    impressions: 25000,
    clicks: 612,
    lastOptimizedAt: "2026-03-06 17:10",
    notes:
      "Completed successfully after full quota delivery and end-of-campaign audit.",
  },
];
