import type { BoostedPost } from "../types/boostedPost";

export const initialBoostedPosts: BoostedPost[] = [
  {
    id: 1,
    postTitle: "Rare Monstera Deliciosa for Sale",
    ownerName: "Nguyen Van A",
    slot: "Home Top",
    packageName: "Homepage Premium 7 Days",
    startDate: "2026-03-15",
    endDate: "2026-03-22",
    status: "Active",
    impressions: 18240,
    clicks: 536,
    remainingQuota: 31760,
    notes: "Main homepage boosted campaign for premium visibility.",
  },
  {
    id: 2,
    postTitle: "Mini Bonsai Collection",
    ownerName: "Tran Thi B",
    slot: "Category Top",
    packageName: "Category Spotlight 5 Days",
    startDate: "2026-03-14",
    endDate: "2026-03-19",
    status: "Paused",
    impressions: 9400,
    clicks: 224,
    remainingQuota: 15600,
    notes: "Paused by admin after campaign review request.",
  },
  {
    id: 3,
    postTitle: "Succulent Combo Pot Set",
    ownerName: "Le Van C",
    slot: "Search Boost",
    packageName: "Search Boost 3 Days",
    startDate: "2026-03-10",
    endDate: "2026-03-13",
    status: "Expired",
    impressions: 15000,
    clicks: 301,
    remainingQuota: 0,
    notes: "Campaign reached end date and expired automatically.",
  },
  {
    id: 4,
    postTitle: "Philodendron Pink Princess Cutting",
    ownerName: "Pham Thi D",
    slot: "Home Top",
    packageName: "Homepage Premium 7 Days",
    startDate: "2026-04-02",
    endDate: "2026-04-09",
    status: "Scheduled",
    impressions: 0,
    clicks: 0,
    remainingQuota: 50000,
    notes: "Upcoming campaign scheduled to start next week.",
  },
  {
    id: 5,
    postTitle: "Ficus Ginseng Decorative Pot",
    ownerName: "Hoang Van E",
    slot: "Category Top",
    packageName: "Category Spotlight 5 Days",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "Completed",
    impressions: 25000,
    clicks: 612,
    remainingQuota: 0,
    notes: "Completed successfully and delivered all configured quota.",
  },
];
