import type { CategoryMapping } from "../types/categoryMapping";

export const initialCategoryMappings: CategoryMapping[] = [
  {
    id: 1,
    categoryId: 1,
    categoryName: "Indoor Plants",
    attributeId: 1,
    attributeName: "Height",
    attributeCode: "height",
    attributeType: "Number",
    required: true,
    displayOrder: 1,
    status: "Active",
  },
  {
    id: 2,
    categoryId: 1,
    categoryName: "Indoor Plants",
    attributeId: 2,
    attributeName: "Pot Size",
    attributeCode: "pot_size",
    attributeType: "Text",
    required: false,
    displayOrder: 2,
    status: "Active",
  },
  {
    id: 3,
    categoryId: 3,
    categoryName: "Succulents",
    attributeId: 3,
    attributeName: "Light Requirement",
    attributeCode: "light_requirement",
    attributeType: "Select",
    required: true,
    displayOrder: 1,
    status: "Active",
  },
  {
    id: 4,
    categoryId: 4,
    categoryName: "Bonsai",
    attributeId: 4,
    attributeName: "Pet Friendly",
    attributeCode: "pet_friendly",
    attributeType: "Boolean",
    required: false,
    displayOrder: 3,
    status: "Disabled",
  },
];
