import type { Promotion } from "../types/promotion";

export const initialPromotions: Promotion[] = [
  {
    id: 1,
    postTitle: "Rare Monstera Deliciosa for Sale",
    owner: "Nguyen Van A",
    slot: "Home Top",
    packageName: "Premium 7 Days",
    startDate: "2026-03-15",
    endDate: "2026-03-22",
    status: "Active",
    budget: "1,200,000 VND",
    note: "Priority placement for premium plant listing on the homepage.",
  },
  {
    id: 2,
    postTitle: "Mini Bonsai Collection",
    owner: "Tran Thi B",
    slot: "Category Top",
    packageName: "Standard 5 Days",
    startDate: "2026-03-14",
    endDate: "2026-03-19",
    status: "Paused",
    budget: "650,000 VND",
    note: "Temporarily paused by admin review due to content adjustment request.",
  },
  {
    id: 3,
    postTitle: "Succulent Combo Pot Set",
    owner: "Le Van C",
    slot: "Search Boost",
    packageName: "Boost 3 Days",
    startDate: "2026-03-10",
    endDate: "2026-03-13",
    status: "Expired",
    budget: "320,000 VND",
    note: "Promotion package completed and no longer active.",
  },
  {
    id: 4,
    postTitle: "Philodendron Pink Princess Cutting",
    owner: "Pham Thi D",
    slot: "Home Top",
    packageName: "Premium 7 Days",
    startDate: "2026-04-02",
    endDate: "2026-04-09",
    status: "Scheduled",
    budget: "1,200,000 VND",
    note: "Scheduled campaign waiting for upcoming placement window.",
  },
];
