import type { Promotion } from "../types/promotion";

export const initialPromotions: Promotion[] = [
  {
    id: 1,
    postId: 12,
    postTitle: "Tùng Bách Tán Lùn Nhật Mini",
    owner: "Nam Định Art Garden",
    packageId: 2,
    slot: "Vị trí 1 trang chủ",
    packageName: "Gói đẩy bài theo tháng vị trí 1 trang chủ",
    startDate: "2026-04-11",
    endDate: "2026-05-10",
    status: "Paused",
    budget: "299,000 VND",
    note: "Chiến dịch đang tạm dừng để admin điều phối lại slot vị trí 1.",
    paymentStatus: "Paid",
    handledBy: "Admin",
    reopenEligible: false,
    canPause: false,
    canResume: true,
    warnings: ["Vị trí 1 chỉ cho 1 bài chạy cùng lúc trong cùng khoảng thời gian."],
  },
  {
    id: 2,
    postId: 10,
    postTitle: "Kim Quýt Bonsai Mini Sai Quả",
    owner: "Vườn Bonsai Phố Huyện",
    packageId: 1,
    slot: "Vị trí 2 trang chủ",
    packageName: "Gói đẩy bài theo tháng vị trí 2 trang chủ",
    startDate: "2026-04-12",
    endDate: "2026-05-11",
    status: "Paused",
    budget: "99,000 VND",
    note: "Chiến dịch chờ cập nhật nội dung trước khi tiếp tục phân phối hiển thị.",
    paymentStatus: "Paid",
    handledBy: "Admin",
    reopenEligible: false,
    canPause: false,
    canResume: true,
    warnings: [],
  },
  {
    id: 3,
    postId: 15,
    postTitle: "Ổi Bonsai Sai Quả Dáng Hoành",
    owner: "Vườn Bonsai Phố Huyện",
    packageId: 2,
    slot: "Vị trí 1 trang chủ",
    packageName: "Gói đẩy bài theo tháng vị trí 1 trang chủ",
    startDate: "2026-04-16",
    endDate: "2026-05-16",
    status: "Active",
    budget: "299,000 VND",
    note: "Chiến dịch đang chạy ổn định và chiếm slot vị trí 1 trên trang chủ.",
    paymentStatus: "Paid",
    handledBy: "Manager",
    reopenEligible: false,
    canPause: true,
    canResume: false,
    warnings: ["Bài đang dùng gói còn hiệu lực nên không thể mua gói khác song song."],
  },
  {
    id: 4,
    postId: 7,
    postTitle: "Si Bonsai Phong Thủy Tài Lộc",
    owner: "Vườn Bonsai Phố Huyện",
    packageId: 1,
    slot: "Vị trí 2 trang chủ",
    packageName: "Gói đẩy bài theo tháng vị trí 2 trang chủ",
    startDate: "2026-04-16",
    endDate: "2026-05-16",
    status: "Active",
    budget: "99,000 VND",
    handledBy: "Manager",
    note: "Chiến dịch đang chiếm vị trí 2 trên trang chủ trong chu kỳ hiện tại.",
    paymentStatus: "Paid",
    reopenEligible: false,
    canPause: true,
    canResume: false,
    warnings: [],
  },
  {
    id: 5,
    postId: 1,
    postTitle: "Sanh Nam Điền Mini Dáng Văn Nhân",
    owner: "Vườn Bonsai Phố Huyện",
    packageId: 3,
    slot: "Vị trí 3 trang chủ",
    packageName: "Gói đẩy bài theo tháng vị trí 3 trang chủ",
    startDate: "2026-04-16",
    endDate: "2026-05-16",
    status: "Active",
    budget: "29,000 VND",
    note: "Chiến dịch đang chạy ở vị trí 3 để tăng hiển thị nhẹ cho bài đăng.",
    paymentStatus: "Paid",
    handledBy: "Manager",
    reopenEligible: false,
    canPause: true,
    canResume: false,
    warnings: [],
  },
];
