import type { Promotion } from "../types/promotion";

export const initialPromotions: Promotion[] = [
  {
    id: 1,
    postTitle: "Rare Monstera Deliciosa for Sale",
    owner: "Nguyen Van A",
    slot: "Home Top",
    packageName: "Premium 7 Days",
    startDate: "2026-03-15",
    endDate: "2026-03-22",
    status: "Active",
    budget: "1,200,000 VND",
    note: "Priority placement for premium plant listing on the homepage.",
    canPause: true,
    canResume: false,
  },
  {
    id: 2,
    postTitle: "Mini Bonsai Collection",
    owner: "Tran Thi B",
    slot: "Category Top",
    packageName: "Standard 5 Days",
    startDate: "2026-03-14",
    endDate: "2026-03-19",
    status: "Paused",
    budget: "650,000 VND",
    note: "Temporarily paused by admin review due to content adjustment request.",
    canPause: false,
    canResume: true,
  },
  {
    id: 3,
    postTitle: "Succulent Combo Pot Set",
    owner: "Le Van C",
    slot: "Search Boost",
    packageName: "Boost 3 Days",
    startDate: "2026-03-10",
    endDate: "2026-03-13",
    status: "Expired",
    budget: "320,000 VND",
    note: "Promotion package completed and no longer active.",
    canPause: false,
    canResume: false,
    pauseBlockedReason: "Expired promotions cannot be paused.",
    resumeBlockedReason: "Expired promotions cannot be resumed.",
  },
  {
    id: 4,
    postTitle: "Philodendron Pink Princess Cutting",
    owner: "Pham Thi D",
    slot: "Home Top",
    packageName: "Premium 7 Days",
    startDate: "2026-04-02",
    endDate: "2026-04-09",
    status: "Scheduled",
    budget: "1,200,000 VND",
    note: "Scheduled campaign waiting for upcoming placement window.",
    canPause: false,
    canResume: false,
    pauseBlockedReason: "Scheduled promotions have not started yet.",
    resumeBlockedReason: "Scheduled promotions do not need resume action.",
  },
  {
    id: 5,
    postTitle: "Variegated Alocasia Showcase",
    owner: "Hoang Van E",
    slot: "Search Boost",
    packageName: "Boost 5 Days",
    startDate: "2026-03-20",
    endDate: "2026-03-25",
    status: "Active",
    budget: "500,000 VND",
    note: "Boosted search visibility for newly approved rare plant listing.",
    canPause: false,
    canResume: false,
    pauseBlockedReason:
      "This promotion is currently in a protected billing window and cannot be paused.",
    resumeBlockedReason:
      "This promotion is already active and does not need resume action.",
  },
  {
    id: 6,
    postTitle: "Snake Plant Starter Bundle",
    owner: "Le Thi F",
    slot: "Category Top",
    packageName: "Standard 7 Days",
    startDate: "2026-03-18",
    endDate: "2026-03-25",
    status: "Paused",
    budget: "700,000 VND",
    note: "Paused while waiting for updated post images from seller.",
    canPause: false,
    canResume: false,
    pauseBlockedReason: "This promotion is already paused.",
    resumeBlockedReason:
      "Cannot resume until the post content review is completed.",
  },
];
