import type { User, UserFormState } from "../types/user";

export const initialUsers: User[] = [
  {
    id: 1,
    fullName: "System Administrator",
    phone: "0900000000",
    email: "admin@greenmarket.vn",
    role: "Manager",
    status: "Active",
    joinedAt: "2026-03-01",
    location: "Ho Chi Minh City",
    lastLoginAt: "2026-03-18 08:15",
    roleAssignments: [
      {
        id: 1,
        role: "Manager",
        assignedBy: "System Setup",
        assignedAt: "2026-03-01",
        note: "Initial manager-aligned seed role.",
      },
    ],
    activityLogs: [
      {
        id: 1,
        action: "Account Created",
        detail: "Protected administrator account was created.",
        performedBy: "System Setup",
        performedAt: "2026-03-01 08:00",
      },
      {
        id: 2,
        action: "Role Assigned",
        detail: "Assigned role: Manager.",
        performedBy: "System Setup",
        performedAt: "2026-03-01 08:01",
      },
    ],
    businessRoleId: 4,
    businessRoleCode: "MANAGER",
    businessRoleTitle: "Manager",
  },
  {
    id: 2,
    fullName: "Nguyen Van A",
    phone: "0912345678",
    email: "vana@greenmarket.vn",
    role: "User",
    status: "Active",
    joinedAt: "2026-03-10",
    location: "Da Nang",
    lastLoginAt: "2026-03-20 09:20",
    roleAssignments: [
      {
        id: 1,
        role: "User",
        assignedBy: "System Administrator",
        assignedAt: "2026-03-10",
        note: "Initial account setup.",
      },
    ],
    activityLogs: [
      {
        id: 1,
        action: "Account Created",
        detail: "User account was created in the admin panel.",
        performedBy: "System Administrator",
        performedAt: "2026-03-10 09:00",
      },
      {
        id: 2,
        action: "Role Assigned",
        detail: "Assigned role: User.",
        performedBy: "System Administrator",
        performedAt: "2026-03-10 09:01",
      },
    ],
    businessRoleId: 1,
    businessRoleCode: "USER",
    businessRoleTitle: "User",
  },
  {
    id: 3,
    fullName: "Tran Thi B",
    phone: "0987654321",
    email: "thib@greenmarket.vn",
    role: "Manager",
    status: "Active",
    joinedAt: "2026-03-11",
    location: "Can Tho",
    lastLoginAt: "2026-03-19 14:10",
    roleAssignments: [
      {
        id: 1,
        role: "Manager",
        assignedBy: "System Administrator",
        assignedAt: "2026-03-11",
        note: "Assigned moderation responsibilities.",
      },
    ],
    activityLogs: [
      {
        id: 1,
        action: "Account Created",
        detail: "User account was created in the admin panel.",
        performedBy: "System Administrator",
        performedAt: "2026-03-11 10:00",
      },
      {
        id: 2,
        action: "Role Assigned",
        detail: "Assigned role: Manager.",
        performedBy: "System Administrator",
        performedAt: "2026-03-11 10:02",
      },
    ],
    businessRoleId: 4,
    businessRoleCode: "MANAGER",
    businessRoleTitle: "Manager",
  },
  {
    id: 4,
    fullName: "Le Van C",
    phone: "0933555777",
    email: "vanc@greenmarket.vn",
    role: "Host",
    status: "Locked",
    joinedAt: "2026-03-12",
    location: "Ha Noi",
    lastLoginAt: "2026-03-17 11:05",
    roleAssignments: [
      {
        id: 1,
        role: "Host",
        assignedBy: "System Administrator",
        assignedAt: "2026-03-12",
        note: "Initial account setup.",
      },
    ],
    activityLogs: [
      {
        id: 1,
        action: "Account Created",
        detail: "User account was created in the admin panel.",
        performedBy: "System Administrator",
        performedAt: "2026-03-12 11:00",
      },
      {
        id: 2,
        action: "Role Assigned",
        detail: "Assigned role: Host.",
        performedBy: "System Administrator",
        performedAt: "2026-03-12 11:01",
      },
      {
        id: 3,
        action: "Account Locked",
        detail: "Account access was restricted by admin review.",
        performedBy: "System Administrator",
        performedAt: "2026-03-18 15:30",
      },
    ],
    businessRoleId: 2,
    businessRoleCode: "HOST",
    businessRoleTitle: "Host",
  },
  {
    id: 5,
    fullName: "Pham Thi D",
    phone: "0977001122",
    email: "thid@greenmarket.vn",
    role: "Collaborator",
    status: "Active",
    joinedAt: "2026-03-13",
    location: "Hue",
    lastLoginAt: "2026-03-21 10:40",
    roleAssignments: [
      {
        id: 1,
        role: "Collaborator",
        assignedBy: "System Administrator",
        assignedAt: "2026-03-13",
        note: "Initial account setup.",
      },
    ],
    activityLogs: [
      {
        id: 1,
        action: "Account Created",
        detail: "User account was created in the admin panel.",
        performedBy: "System Administrator",
        performedAt: "2026-03-13 13:00",
      },
      {
        id: 2,
        action: "Role Assigned",
        detail: "Assigned role: Collaborator.",
        performedBy: "System Administrator",
        performedAt: "2026-03-13 13:01",
      },
    ],
    businessRoleId: 3,
    businessRoleCode: "COLLABORATOR",
    businessRoleTitle: "Collaborator",
  },
  {
    id: 6,
    fullName: "Hoang Van E",
    phone: "0944112233",
    email: "vane@greenmarket.vn",
    role: "Operation Staff",
    status: "Active",
    joinedAt: "2026-03-14",
    location: "Hai Phong",
    lastLoginAt: "2026-03-22 16:50",
    roleAssignments: [
      {
        id: 1,
        role: "Operation Staff",
        assignedBy: "System Administrator",
        assignedAt: "2026-03-14",
        note: "Assigned operations support responsibilities.",
      },
    ],
    activityLogs: [
      {
        id: 1,
        action: "Account Created",
        detail: "User account was created in the admin panel.",
        performedBy: "System Administrator",
        performedAt: "2026-03-14 14:00",
      },
      {
        id: 2,
        action: "Role Assigned",
        detail: "Assigned role: Operation Staff.",
        performedBy: "System Administrator",
        performedAt: "2026-03-14 14:02",
      },
    ],
    businessRoleId: 5,
    businessRoleCode: "OPERATION_STAFF",
    businessRoleTitle: "Operation Staff",
  },
];

export const emptyUserForm: UserFormState = {
  fullName: "",
  email: "",
  role: "User",
};
