import { exportService } from "../services/exportService";
import "./ExportPage.css";

function ExportPage() {
  const historyItems = exportService.getExportHistory();

  return (
    <div className="export-page">
      <div className="export-page__header">
        <div>
          <h2>Export CSV</h2>
          <p>Export operational and financial reports for GreenMarket admin.</p>
        </div>
      </div>

      <div className="export-grid">
        <section className="export-card">
          <div className="export-card__header">
            <h3>General Data Export</h3>
            <p>Export operational records from the admin system.</p>
          </div>

          <div className="export-form">
            <div className="export-field">
              <label htmlFor="general-module">Module</label>
              <select id="general-module" defaultValue="Users">
                <option>Users</option>
                <option>Categories</option>
                <option>Attributes</option>
                <option>Templates</option>
                <option>Promotions</option>
                <option>Analytics</option>
              </select>
            </div>

            <div className="export-field">
              <label htmlFor="general-date-range">Date Range</label>
              <select id="general-date-range" defaultValue="Last 30 Days">
                <option>Last 7 Days</option>
                <option>Last 30 Days</option>
                <option>Last 90 Days</option>
                <option>This Year</option>
              </select>
            </div>

            <div className="export-field">
              <label htmlFor="general-format">File Format</label>
              <select id="general-format" defaultValue="CSV">
                <option>CSV</option>
                <option>XLSX</option>
              </select>
            </div>

            <button className="export-button" type="button">
              Export General Data
            </button>
          </div>
        </section>

        <section className="export-card">
          <div className="export-card__header">
            <h3>Financial Export</h3>
            <p>Export revenue and customer spending reports.</p>
          </div>

          <div className="export-form">
            <div className="export-field">
              <label htmlFor="financial-report-type">Report Type</label>
              <select id="financial-report-type" defaultValue="Revenue Summary">
                <option>Revenue Summary</option>
                <option>Customer Spending Report</option>
                <option>Promotion Performance</option>
              </select>
            </div>

            <div className="export-field">
              <label htmlFor="financial-date-range">Date Range</label>
              <select id="financial-date-range" defaultValue="Last 30 Days">
                <option>Last 7 Days</option>
                <option>Last 30 Days</option>
                <option>Last 90 Days</option>
                <option>This Year</option>
              </select>
            </div>

            <div className="export-field">
              <label htmlFor="financial-format">File Format</label>
              <select id="financial-format" defaultValue="CSV">
                <option>CSV</option>
                <option>XLSX</option>
              </select>
            </div>

            <button className="export-button" type="button">
              Export Financial Report
            </button>
          </div>
        </section>
      </div>

      <section className="export-history-card">
        <div className="export-card__header">
          <h3>Recent Export History</h3>
          <p>Track recently generated reports.</p>
        </div>

        <div className="export-history-table-wrapper">
          <table className="export-history-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Report Name</th>
                <th>Type</th>
                <th>Format</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Status</th>
              </tr>
            </thead>

            <tbody>
              {historyItems.map((item) => (
                <tr key={item.id}>
                  <td>#{item.id}</td>
                  <td>{item.reportName}</td>
                  <td>{item.type}</td>
                  <td>{item.format}</td>
                  <td>{item.generatedBy}</td>
                  <td>{item.date}</td>
                  <td>
                    <span
                      className={
                        item.status === "Completed"
                          ? "export-badge export-badge--success"
                          : "export-badge export-badge--processing"
                      }
                    >
                      {item.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

export default ExportPage;
